export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const FETCH_TMPS_REQUEST = "FETCH_TMPS_REQUEST";
export const FETCH_TMPS_SUCCESS = "FETCH_TMPS_SUCCESS";
export const FETCH_TMPS_FAILURE = "FETCH_TMPS_FAILURE";
